location: uksouth
resourceGroup: "aso-sample-rg"
tags:
  teamName: "test"
  applicationName: "test"
  builtFrom: "test"
  businessArea: "test"
  environment: "test"
secretNameSuffix: "test"
setup:
  containers:
   - container1
   - container22
