{{- $globals := .Values.global | default dict -}}
{{- $tags := $globals.tags | default dict -}}
---
apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccount
metadata:
  name: {{ template "hmcts.blobstorage.storageAccountName" . }}
spec:
  location:  {{ .Values.location }}
  kind: BlobStorage
  sku:
    name: Standard_LRS
  owner:
    name: {{ required "A resource group ( .Values.resourceGroup ) is required for storage creation" .Values.resourceGroup | quote }}
  accessTier: Hot
  tags:
    app.kubernetes.io_name: {{ template "hmcts.blobstorage.releaseName" . }}
    helm.sh_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    application: {{ required "An application tag name (.Values.tags.applicationName) is required"  (.Values.tags.applicationName | default $tags.applicationName) }}
    builtFrom: {{ required "Repo built from (.Values.tags.builtFrom) is required" (.Values.tags.builtFrom | default $tags.builtFrom) }}
    businessArea: {{ required "Business Area name (.Values.tags.businessArea) is required" (.Values.tags.businessArea | default $tags.businessArea) }}
    environment: {{ required "Environment name (.Values.tags.environment) is required" (.Values.tags.environment | default $tags.environment) }}
  # Optional: Save the keys for the storage account into a Kubernetes secret
  operatorSpec:
    secrets:
      key1:
        name: storage-secret-{{ template "hmcts.blobstorage.releaseName" . }}
        key: accessKey
      key2:
        name: storage-secret-{{ template "hmcts.blobstorage.releaseName" . }}
        key: key2
      blobEndpoint:
        name: storage-secret-{{ template "hmcts.blobstorage.releaseName" . }}
        key: blobEndpoint
  supportsHttpsTrafficOnly: {{  .Values.setup.supportsHttpsTrafficOnly | default true }}

---
apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccountsBlobService
metadata:
  name: storage-blobservice-{{ template "hmcts.blobstorage.releaseName" . }}
spec:
  owner:
    name: {{ template "hmcts.blobstorage.storageAccountName" . }}


{{- range .Values.setup.containers }}
---
apiVersion: storage.azure.com/v1beta20210401
kind: StorageAccountsBlobServicesContainer
metadata:
  name: {{ template "hmcts.blobstorage.storageContainerPrefix" . }}-{{ . }}
spec:
  owner:
    name: storage-blobservice-{{ template "hmcts.blobstorage.releaseName" $ }}
  azureName: {{ . }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: storage-account-{{ template "hmcts.blobstorage.releaseName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "hmcts.blobstorage.releaseName" . }}
type: Opaque
data:
  storage_account_name: {{ include "hmcts.blobstorage.storageAccountName" . | b64enc | quote }}
