---
#
# Service Catalog Blob storage namespace
# https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/storage.md
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: storage-service-{{ template "hmcts.blobstorage.releaseName" . }}
  labels:
    {{- ( include "hmcts.blobstorage.labels" . ) | indent 4 }}
spec:
  clusterServiceClassExternalName: azure-storage-blob-storage-account
  clusterServicePlanExternalName: account
  parameters:
    location: {{ .Values.location }}
    alias: storage-account-{{ template "hmcts.blobstorage.releaseName" . }}
    resourceGroup: {{ required "A resource group ( .Values.resourceGroup ) is required for storage creation" .Values.resourceGroup | quote }}
    enableNonHttpsTraffic: {{ .Values.enableNonHttpsTraffic | default "disabled" | quote }}
    tags:
      app.kubernetes.io_name: {{ template "hmcts.blobstorage.releaseName" . }}
      helm.sh_chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      "Team Name": {{ required "A team name (.Values.teamName) is required" .Values.teamName }}
      application: {{ required "Application tag (.Values.applicationName) is required" .Values.applicationName }}
      builtFrom: {{ required "Built from tag (.Values.builtFrom) is required" .Values.builtFrom }}
      businessArea: {{ required "Business area (.Values.builtFrom) is required" .Values.builtFrom }}
      environment: {{ required "Environment tag (.Values.builtFrom) is required" .Values.builtFrom }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: storage-binding-{{ template "hmcts.blobstorage.releaseName" . }}
  labels:
    {{- ( include "hmcts.blobstorage.labels" . ) | indent 4 }}
spec:
  instanceRef:
    name: storage-service-{{ template "hmcts.blobstorage.releaseName" . }}
  secretName: storage-secret-{{ template "hmcts.blobstorage.releaseName" . }}

{{- if .Values.setup -}}
  {{- if .Values.setup.containers -}}
    {{- $base := . -}}
    {{ range .Values.setup.containers }}

---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: container-{{ template "hmcts.blobstorage.releaseName" $base }}-{{ required "All .Values.setup.containers items need a 'name' property" . }}
  labels:
    {{- ( include "hmcts.blobstorage.labels" $base ) | indent 4 }}
spec:
  clusterServiceClassExternalName: azure-storage-blob-container
  clusterServicePlanExternalName: container
  parameters:
    parentAlias: storage-account-{{ template "hmcts.blobstorage.releaseName" $base }}
    containerName: {{ . }}
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: container-binding-{{ template "hmcts.blobstorage.releaseName" $base }}-{{ . }}
  labels:
    {{- (include "hmcts.blobstorage.labels" $base) | indent 4 }}
spec:
  instanceRef:
    name: container-{{ template "hmcts.blobstorage.releaseName" $base }}-{{ . }}
  secretName: container-secret-{{ template "hmcts.blobstorage.releaseName" $base }}-{{ . }}
    {{ end }}
  {{- end -}}
{{- end -}}
