# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: storage-account-{{ template "hmcts.blobstorage.releaseName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ template "hmcts.blobstorage.releaseName" . }}
type: Opaque
data:
  storage_account_name: {{ $stgname | b64enc | quote }}
